name: Build and Release Godot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Godot 4.3 RC3
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_linux.x86_64.zip
          unzip Godot_v4.3-rc3_linux.x86_64.zip -d godot
          sudo mv godot/Godot_v4.3-rc3_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.3.rc3
          unzip -o Godot_v4.3-rc3_export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.rc3
          mv ~/.local/share/godot/export_templates/4.3.rc3/templates/* ~/.local/share/godot/export_templates/4.3.rc3/
          rmdir ~/.local/share/godot/export_templates/4.3.rc3/templates

      - name: Debug Export Templates
        run: |
          echo "Verifying export templates:"
          ls -la /home/runner/.local/share/godot/export_templates/4.3.rc3/

      - name: Create Build Directory
        run: mkdir -p build

      - name: Export Web Build
        run: |
          godot --headless --export-release "Web" build/index.html
        env:
          GODOT_PASSWORD: ${{ secrets.GODOT_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Build
          path: build/

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "Creating tag $TAG_NAME"
          git tag $TAG_NAME
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
