name: Build and Release Godot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Godot 4.3 RC3
        uses: yeslayla/build-godot-action@v1.4.1
        with:
          godot-version: '4.3-rc3' # Use the specific version you are working with
          export-templates: true

      - name: Export HTML5 Build
        run: |
          godot --headless --export-release "HTML5" build/index.html
        env:
          GODOT_PASSWORD: ${{ secrets.GODOT_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Build
          path: build/ # Ensure this matches the output path of your exported build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/* # Add all build files to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
