name: Build and Release Godot for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Godot 4.3 RC3
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_linux.x86_64.zip
          unzip Godot_v4.3-rc3_linux.x86_64.zip -d godot
          sudo mv godot/Godot_v4.3-rc3_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.3.rc3
          unzip -o Godot_v4.3-rc3_export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.rc3
          mv ~/.local/share/godot/export_templates/4.3.rc3/templates/* ~/.local/share/godot/export_templates/4.3.rc3/
          rmdir ~/.local/share/godot/export_templates/4.3.rc3/templates
      # Create build directory
      - name: Create Build Directory
        run: mkdir -p build

      # Export the Windows Build
      - name: Export Windows Build
        run: |
          godot --headless --export-release "Windows Desktop" build/game.exe
        env:
          GODOT_PASSWORD: ${{ secrets.GODOT_PASSWORD }}

      # Create a Zip Archive for the Build
      - name: Create Zip Archive
        run: |
          zip -r build/game.zip build/

      # Upload the Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Windows-Build
          path: build/game.zip

      # Create Git Tag
      - name: Create Git Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "Creating tag $TAG_NAME"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $TAG_NAME
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      # Create a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/game.zip
          tag_name: ${{ env.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
