name: Build and Release Godot for Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Godot 4.3 RC3
        run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_linux.x86_64.zip
          unzip Godot_v4.3-rc3_linux.x86_64.zip -d godot
          sudo mv godot/Godot_v4.3-rc3_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot

      - name: Install Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.3.rc3
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_export_templates.tpz
          unzip -o Godot_v4.3-rc3_export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.rc3

      - name: Create Build Directory
        run: mkdir -p build

      - name: Export Windows Build
        run: |
          godot --headless --export-release "Windows Desktop" build/game.exe
        env:
          GODOT_PASSWORD: ${{ secrets.GODOT_PASSWORD }}

      - name: Create Zip Archive
        run: |
          zip -r build/game.zip build/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Windows-Build
          path: build/game.zip
