name: Build Godot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Godot
        uses: yeslayla/build-godot-action@v1.4.1
        with:
          name: "MyGame" # Replace with your exported binary name
          preset: "HTML5" # Replace with your desired export preset
          subdirectory: "build" # Optional: Specify a subdirectory for the exported project
          package: true # Set true to output an artifact zip file
          projectDir: "./game" # Location of your Godot project in the repository
          debugMode: false # Set true if exporting in debug mode
