name: Build and Release Godot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Godot 4.3 RC3
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/rc3/Godot_v4.3-rc3_linux_headless.64.zip
          unzip Godot_v4.3-rc3_linux_headless.64.zip -d godot
          sudo mv godot/Godot_v4.3-rc3_linux_headless.64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot
          wget https://github.com/godotengine/godot-builds/releases/download/4.3-rc3/Godot_v4.3-rc3_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates
          unzip Godot_v4.3-rc3_export_templates.tpz -d ~/.local/share/godot/export_templates

      - name: Export HTML5 Build
        run: |
          godot --headless --export-release "HTML5" build/index.html
        env:
          GODOT_PASSWORD: ${{ secrets.GODOT_PASSWORD }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Godot-Build
          path: build/ # Ensure this matches the output path of your exported build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
